name: tests
on: [pull_request, push, workflow_dispatch]
jobs:
  run-tests:
    name: Perform tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Show Python version
        run: python3 -VV
      - name: Install testing dependencies
        run: python3 -m pip install --upgrade pip pytest
      - name: Run tests
        run: python3 -m pytest tests/
